// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'apikey-prompt-message'
  | 'apikey-prompt-title'
  | 'apikey-saved'
  | 'cli-not-found'
  | 'pref-apikey'
  | 'pref-category'
  | 'pref-debug'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
